### ISSUE TITLE
Tolerance of root finding

### ISSUE THREAD

**Issue by adityam** [JuliaLang/Roots.jl#21]
Is it possible to specify a tolerance for `fzero` so that it returns `x` if `|f(x)| < tolerance` rather than `f(x) == 0.0`. 
My use case is the following. I want to find `x` such that `f(x) \approx g(x)`, where `f` is the solution of a Integral equation, which is computed approximately to be within a tolerance. I can try to find `x` by finding roots of 
```
h(x) = f(x) - g(x)
```
However, this may not converge because calling `f(x)` gives an approximate value.

**Comment by stevengj** [comment]
We definitely shouldn't rely on `f` being exactly zero at the root.   There should be at least four stopping criteria:

* `ftol`: stop when `|f| ≤ ftol`
* `xtolrel` and `xtolabs`: stop when `|Δx| ≤ max(xtolabs, |x| * xtolrel)`
* `maxeval`: stop when the number of function evaluations exceeds `maxeval`.

**Comment by jverzani** [comment]
Thanks, the final call from `fzero(f::Function, x0::Real)` had a stringent tolerance. It wasn't 0, but basically was. It is now relaxed and can be adjusted with `tol` (not `ftol`, as other uses of `tol` are already present).

**Comment by adityam** [comment]
Thanks!
