### ISSUE TITLE
Incorrect return results from some non-default methods

### ISSUE THREAD

**Issue by ikirill** [JuliaLang/Roots.jl#25]
The testing output in #22 shows that some methods return incorrect roots without failing with an error.

It is a bug that a method, used with default settings, can return incorrect results without throwing an error.

**Comment by ViralBShah** [comment]
@ikirill I just invited you to be a contributor on Roots.jl.

**Comment by jverzani** [comment]
Thanks for your attention here @ikirill. This should be addressed with 719fc2bb9c8fb6e85759d6e2e8208e34f6a5973a.

**Comment by ikirill** [comment]
@ViralBShah  Thank you! What does that mean?
