### ISSUE TITLE
Excessive number of iterations on testing functions

### ISSUE THREAD

**Issue by ikirill** [JuliaLang/Roots.jl#26]
See the data in #22.

The default fzero method takes about 9k total evaluations, whereas the original paper lists a figure on the order of 3k. So there is reason to think that 9k is too many: termination conditions, and default settings, might be overly strict.

**Comment by jverzani** [comment]
Thanks, this should be cut down now with 719fc2bb9c8fb6e85759d6e2e8208e34f6a5973a. Your testing functions were very helpful.
