### ISSUE TITLE
Roots is failing on load for julia v.0.3?

### ISSUE THREAD

**Issue by vgupta1** [JuliaLang/Roots.jl#27]
Hi all,

I fire up julia v.0.3 and call using Roots and the following error.  Any ideas?

```
julia> using Roots
ERROR: syntax: "function" at /Users/vishalgupta/.julia/v0.3/Docile/src/method-lookup.jl:186 expected "end", got "elseif"
 in include at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include! at /Users/vishalgupta/.julia/v0.3/Docile/src/Docile.jl:68
 in anonymous at /Users/vishalgupta/.julia/v0.3/Docile/src/Docile.jl:96
 in include at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/vishalgupta/.julia/v0.3/Docile/src/method-lookup.jl, in expression starting on line 189
while loading /Users/vishalgupta/.julia/v0.3/Docile/src/Docile.jl, in expression starting on line 104
while loading /Users/vishalgupta/.julia/v0.3/Roots/src/Roots.jl, in expression starting on line 9
```

**Comment by ViralBShah** [comment]
Cc: @michaelhatherly

**Comment by vgupta1** [comment]
If it helps diagnose, rolling back one version (to 1.1.09) seems to fix the problem.

**Comment by ViralBShah** [comment]
@vgupta1 Can you run `Pkg.update()`? I just did and it loads fine.

**Comment by MichaelHatherly** [comment]
Loading fine for me as well. @vgupta1 what's your output from `versioninfo()`?

**Comment by vgupta1** [comment]
Looks like this:

Julia Version 0.3.0
Commit 7681878* (2014-08-20 20:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.3.0)
  CPU: Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by MichaelHatherly** [comment]
Thanks for the info. Not sure if something has change during the 0.3 release that could have caused this since that build is from a few months ago -- shouldn't be a problem though. I'll rebuild on that commit and check.

What version of Docile.jl have you got? (From the backtrace it does look like the most recent version.)

**Comment by MichaelHatherly** [comment]
Can reproduce on that commit:

```
julia> versioninfo()
Julia Version 0.3.0
Commit 7681878 (2014-08-20 20:43 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY HASWELL)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> using Roots
ERROR: syntax: "function" at /home/mike/.julia/v0.3/Docile/src/method-lookup.jl:186 expected "end", got "elseif"
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include! at /home/mike/.julia/v0.3/Docile/src/Docile.jl:68
 in anonymous at /home/mike/.julia/v0.3/Docile/src/Docile.jl:96
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/mike/.julia/v0.3/Docile/src/method-lookup.jl, in expression starting on line 189
while loading /home/mike/.julia/v0.3/Docile/src/Docile.jl, in expression starting on line 104
while loading /home/mike/.julia/v0.3/Roots/src/Roots.jl, in expression starting on line 9
```

I'll look into what's causing this.

**Comment by vgupta1** [comment]
Seems to be

Docile                        0.4.5


Thanks for the help.  I should have mentioned earlier, this is non-urgent.
It runs fine on 1.1.09, and that's good enough for me for now.  (Just doing
personal development.)  And it seems that if I just updated my build of
v.03 it would fix the problem.


VG

**Comment by vgupta1** [comment]
Thanks Michael!

**Comment by MichaelHatherly** [comment]
Yeah, updating Julia should solve this for you. I'd rather not have this one lurking around though :)

**Comment by MichaelHatherly** [comment]
It appears to be a temporary regression in Julia's parser on that commit (or perhaps it was always like that). The offending line is https://github.com/MichaelHatherly/Docile.jl/blob/689a10646e38a708b309b35a89bc48211d9960f7/src/method-lookup.jl#L187. The `end` in `arg ≡ :end` isn't getting quoted. I'll have a fix done shortly.

**Comment by MichaelHatherly** [comment]
Latest tag (0.4.6) of Docile should resolve this issue for you @vgupta1.

**Comment by vgupta1** [comment]
Thanks Michael. you're a prince.
