### ISSUE TITLE
BUG in a42a?

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaLang/Roots.jl#28]
Here is a (partial) traceback:

```
ERROR: UndefVarError: e not defined
 in a42a at /Users/sglyon/.julia/v0.4/Roots/src/fzero.jl:165
 in fzero at /Users/sglyon/.julia/v0.4/Roots/src/Roots.jl:114
```

I've looked over and over this function and cannot figure out why this is happening. The `&&` should short-circuit so the `distinct(f, a, b, d, e)` should only run after the first iteration has completed. Then `e` is defined towards the end of every iteration, so by the time this ever executes `e` should be in scope...

EDIT: [link](https://github.com/JuliaLang/Roots.jl/blob/master/src/fzero.jl#L165) to the line in question

**Comment by yuyichao** [comment]
I think the scope of the variable does not escape the iteration unless you specify so.

```julia
julia> function k1()
           for i in 1:3
               i == 1 || println(f)
               f = 1
           end
       end
k1 (generic function with 1 method)

julia> function k2()
           local f
           for i in 1:3
               i == 1 || println(f)
               f = 1
           end
       end
k2 (generic function with 1 method)

julia> k1()
ERROR: UndefVarError: f not defined
 in k1 at ./none:3

julia> k2()
1
1
```

**Comment by spencerlyon2** [comment]
Hmm that's subtle. I didn't know that.

**Comment by yuyichao** [comment]
Yeah. The document of the scope definitely needs more comprehensive documentation https://github.com/JuliaLang/julia/issues/9955

**Comment by jverzani** [comment]
Hopefully this f5f3789c07d8cdfa2d6b2c80b175bf1c2649d931 fixes the issue. (I couldn't reproduce the error to be sure.)
