### ISSUE TITLE
Ambiguous Error Message: ERROR: [a,b] is not a bracket

### ISSUE THREAD

**Issue by alejandroschuler** [JuliaLang/Roots.jl#29]
When the bracket includes the true zero, the return is correct, but when it does not, it throws an error which does not reflect what happened. On the other hand, when the bracket really is badly formed, often the error isn't thrown at all and a nonsense answer is returned:

```julia
julia> f = x->x+exp(x)
(anonymous function)

julia> using Roots

julia> fzero(f, [0,1])
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:104

julia> fzero(f,0,1)
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97

julia> fzero(f,-50,50)
-0.5671432904097838

julia> fzero(f,[-50,50])
-0.5671432904097838

julia> fzero(f,0,[-50,50])
-0.5671432904097838

julia> fzero(f,0,1)
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97

julia> fzero(f,[0,1])
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:104

julia> fzero(f,-1,1)
-0.5671432904097838

julia> fzero(f,-1,-1)
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97

julia> fzero(f,-1,-2)
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97

julia> fzero(f,-1,-0.5)
-0.5671432904097838

julia> fzero(f,-1,0)
-0.5671432904097838

julia> fzero(f,[0,5])
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:104

julia> 

julia> fzero(f,-.5,0)
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97

julia> fzero(f,-.6,0)
-0.5671432904097838

julia> fzero(f,0,-.6)
-0.6

julia> fzero(f,0,-1)
-1.0

julia> fzero(f,[0,-1])
-1.0

julia> fzero(f,[-1,-5])
ERROR: [a,b] is not a bracket
 in find_zero at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:65
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:97
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:104

julia> fzero(f,[-0.5,-5])
-0.5
```

**Comment by alejandroschuler** [comment]
Also this is clearly bad:

```julia
julia> fzero(f,0,[-100000, 100000])
ERROR: c must be in (a,b)
 in bracket at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:250
 in a42a at /Users/aschuler/.julia/v0.3/Roots/src/fzero.jl:172
 in fzero at /Users/aschuler/.julia/v0.3/Roots/src/Roots.jl:114

julia> fzero(f,[-100000, 100000])
-0.5671432904097838
```

**Comment by DSLituiev** [comment]
to me, the things appeared even more strange then described above. Though I have `c` within `[a,b]`, when the interval contains a singular point of the function, I am getting this error:

    using Calculus
    C = -0.036377442566655
    F(b) = derivative(zeta, b) / zeta(b)
    g(x) = F(x) - C
    
    using Roots
    
    beta_root =  fzero(g, 1+eps(1.0), BETAMAX)

returns:

    ERROR: [a,b] is not a bracket
     in find_zero at /Users/dlituiev/.julia/v0.3/Roots/src/fzero.jl:65
     in fzero at /Users/dlituiev/.julia/v0.3/Roots/src/Roots.jl:100

While

    beta_root =  fzero(g, 4.66, [1.0000001, 10.0])
returns

    ERROR: c must be in (a,b)
     in bracket at /Users/dlituiev/.julia/v0.3/Roots/src/fzero.jl:250
     in a42a at /Users/dlituiev/.julia/v0.3/Roots/src/fzero.jl:187
     in fzero at /Users/dlituiev/.julia/v0.3/Roots/src/Roots.jl:117

**Comment by jverzani** [comment]
I think you are misunderstanding what a "bracket" is. You need to have a change of sign between f(a) and f(b). In this example, both g(1 + eps()) and g(10.0)  are positive. 

The example `fzero(f,0,[-100000, 100000])` is a bad one, as f(100000) evaluates to `Inf`. You need to have `sign(f(a)) * sign(f(b)) < 0` and `-Inf < f(a) < Inf` and  `-Inf < f(b) < Inf` for a bracket.

I think a better error message is due.

**Comment by jverzani** [comment]
Some better error messages appear with 079eaf66a1573108a552e78641b51e3b187e0d8e
