### ISSUE TITLE
Newton's method may accept complex initial guesses (?)

### ISSUE THREAD

**Issue by vagoberto** [JuliaLang/Roots.jl#30]
Newton's method should work for complex roots. Is there any trouble in to change `x0::Real` to `x0::Number` in the newton routines?

**Comment by jverzani** [comment]
It doesn't quite fit in with the description of the package (function f:R -> R). I tried just changing `Real` to `Number` and ran into issues with the tolerance. It would be a bit more work than just changing the type. If you want to put together a pull request with the changes, it doesn't 'seem unreasonable.

**Comment by vagoberto** [comment]
I opened a pull request with some changes. I successfully tested `newton(f, df, x0::Complex)` with different functions f(x), for example:

    f(x) = x^3 - 1.
    df(x) = 3.0x^2
    
    z = newton(f, df, 0.5+im)     # (Complex{Float64}) -0.5 - 0.8660254037844386im	 
    y = newton(f, df, 0.5)        # (Float64) 1.0

What do you think? :)
