### ISSUE TITLE
Derivative-free methods fail if function is constant on interval

### ISSUE THREAD

**Issue by RogerCrocker** [JuliaLang/Roots.jl#33]
Hi,

The derivative-free methods seem to have troubles finding roots of functions that are constant on some interval. I tried with this simple function, which is continuous and nondecreasing.
    
    julia> using Roots
    julia> f(x) = 1 + x*(x<0) + (x^2-4)*(x>2);
    julia> fzero(f,1)
    ERROR: ConvergenceFailed("f(a) must be finite")
     in have_bracket at /home/.../.julia/v0.3/Roots/src/SOLVE.jl:86
     in have_bracket at /home/.../.julia/v0.3/Roots/src/SOLVE.jl:82
     in secant_method_no_bracket at /home/.../.julia/v0.3/Roots/src/SOLVE.jl:184
     in SOLVE at /home/.../.julia/v0.3/Roots/src/SOLVE.jl:48
     in derivative_free at /home/.../.julia/v0.3/Roots/src/derivative_free.jl:461
     in fzero at /home/.../.julia/v0.3/Roots/src/Roots.jl:67

None of the derivative-free methods is able to find the root at -1 if the initial guess is larger than zero. Some throw errors, some return Inf.

**Comment by jverzani** [comment]
@RogerCrocker: Yeah, that is a problem with the algorithms. Most of them replace a derivative with a secant line approximation somewhere along the way. For a flat function this will introduce a division by 0, and hence the error. Not sure how to work around that in general. If you know a bracket for the function, you could use the bisection method.
